export enum ErrorCodes {
    USER_NOT_FOUND =  "USER_NOT_FOUND",
    BOOK_NOT_FOUND =  "BOOK_NOT_FOUND",
    BOOK_ALREADY_BORROWED = "BOOK_ALREADY_BORROWED",
    BOOK_ALREADY_RETURNED = "BOOK_ALREADY_RETURNED",
    BOOK_NOT_BORROWED = "BOOK_NOT_BORROWED"
}